apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-app.secretName" . }}
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secret.jwtRefreshSecret | quote }}
