apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-app-config
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: ecommerce
  DB_USER: postgres
  FRONTEND_ORIGIN: http://frontend.local
  PORT: "8080"
